name: Build LaTeX document
permissions:
  contents: write
on:
  push:
    tags:
      - '*'
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv.tex
          latexmk_use_lualatex: true
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: cv.pdf
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: cv.pdf
      - name: Push to matteocali.github.io
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: cv.pdf # The folder the action should deploy.
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          repository-name: matteocali/matteocali.github.io
